# Default values for backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: pishapeddevacr01.azurecr.io/backend
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "20231026.10"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "backend"

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
