apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-app
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infrastructure/apps/frontend
    repoURL: git@github.com:HieuTran2NT/sd4345_azure_infrastructure.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      releaseName: frontend-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

