apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-backend
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-backend
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: infrastructure/apps/backend
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}