apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-frontend
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: image=pishapeddevacr01.azurecr.io/frontend
    argocd-image-updater.argoproj.io/image.pull-secret: pullsecret:default/acr-secret-pull
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/image.update-strategy: latest
spec:
  destination:
    namespace: helm-frontend
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: infrastructure/apps/frontend
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true