apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  destination:
    namespace: ingress-nginx
    server: {{ .Values.spec.destination.server }}
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

  source:
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.8.3
    chart: ingress-nginx
 