apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-system
spec:
  destination:
    namespace: istio-system
    server: {{ .Values.spec.destination.server }}
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  sources:
  - repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.19.3
    chart: istiod
    helm:
      valueFiles:
      - $values/infrastructure/argocd-application/values-istio.yaml
  - repoURL: 'git@github.com:HieuTran2NT/sd4345_azure_infrastructure.git'
    targetRevision: HEAD
    ref: values