apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-system
spec:
  destination:
    namespace: istio-system
    server: {{ .Values.spec.destination.server }}
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  source:
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.19.3
    chart: istio
